# Generated by Django 2.0.9 on 2018-11-18 19:10

from django.db import migrations, models
import django.db.models.deletion
import spendesk.wallets.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('EUR', 'Euros'), ('USD', 'US Dollars'), ('GBP', 'British Pound')], max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(default=spendesk.wallets.models.Card.random_card_number, max_length=16, unique=True)),
                ('ccv', models.CharField(default=spendesk.wallets.models.Card.random_ccv, max_length=3)),
                ('is_blocked', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('expires_on', models.DateField(default=spendesk.wallets.models.Card.get_expiry_date)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('origin_currency', models.CharField(choices=[('EUR', 'Euros'), ('USD', 'US Dollars'), ('GBP', 'British Pound')], max_length=3)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_currency', models.CharField(choices=[('EUR', 'Euros'), ('USD', 'US Dollars'), ('GBP', 'British Pound')], max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=1, max_digits=15)),
                ('conversion_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('origin_entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('origin_entity_type', models.CharField(choices=[('C', 'card'), ('W', 'wallet'), ('E', 'external')], max_length=1)),
                ('target_entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('target_entity_type', models.CharField(choices=[('C', 'card'), ('W', 'wallet'), ('E', 'external')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('EUR', 'Euros'), ('USD', 'US Dollars'), ('GBP', 'British Pound')], max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.UUIDField(db_index=True)),
                ('is_master', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['currency', 'is_master'], name='wallets_wal_currenc_ee9b4b_idx'),
        ),
        migrations.AddField(
            model_name='card',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='wallets.Wallet'),
        ),
    ]
