# Generated by Django 2.0.9 on 2018-11-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wallet',
            name='wallets_wal_currenc_ee9b4b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('currency', 'is_master')},
        ),
    ]
